name: Reusable workflows

on:
  workflow_call:
    secrets:
      GOOGLE_CREDENTIALS:
        description: 'A token passed from the caller workflow'
        required: true
  push:
    branches:
    - main
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: suresh200819/GitHub-Actions-Test/.github/workflows/deploy.yml@main
