name: Reusable workflows

on:
  workflow_call:
  push:
    branches:
    - main
  pull_request:

jobs:
  call-workflow-passing-data:
    uses: suresh200819/GitHub-Actions-Test/.github/workflows/deploy.yml@main
    secrets: inherit
